# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[processes]
  worker = "server"

[[mounts]]
  source = "mollysocket_data"
  destination = "/app"
  initial_size = "3GB"
  auto_extend_size_threshold = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
  processes = ["worker"]
