# fly.toml app configuration file generated for mollysocket-fragrant-water-7601 on 2023-12-29T18:28:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mollysocket-fragrant-water-7601"
primary_region = "arn"

[build]

[[mounts]]
  source = "mollysocket_data"
  destination = "/app"
  initial_size = "3GB"
  auto_extend_size_threshold = 0

[[services]]
# no network services being provided.
# we don't even want this app to be accessible from the internet.

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
