# fly.toml app configuration file generated for mollysocket-fragrant-water-7601 on 2023-12-27T20:24:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mollysocket-fragrant-water-7601"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
