name: Deploy

on:
  schedule:
    - cron: "41 2 * * 1"  # every Monday at 02:41 UTC   https://crontab.guru/#41_2_*_*_1
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@1.5
    - run: flyctl deploy --app "${{ secrets.FLY_APP }}" --config fly.template.toml --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
